[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
    esp32async/AsyncTCP@^3.3.5
    esp32async/ESPAsyncWebServer@^3.7.0

build_flags = 
    -D USER_SETUP_LOADED=1
    -D ST7735_DRIVER=1
    -D ST7735_GREENTAB=1
    -D TFT_WIDTH=128
    -D TFT_HEIGHT=160
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=2
    -D TFT_RST=4
    -D SPI_FREQUENCY=27000000
    ; Core fixes for Async Server Serial logging & buffer safety
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
    -D CONFIG_ASYNC_TCP_USE_WDT=0